# Generated by Django 4.2 on 2023-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='NoOfMovies',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
